### ISSUE TITLE
滑动窗口[left, right] 和[left, right)

### ISSUE THREAD

**Issue by Ricardo-609** [itcharge/LeetCode-Py#4]
https://github.com/itcharge/LeetCode-Py/blob/b36df61e5824ca6248fb22acd26bc451ea965c9f/Contents/01.Array/05.Array-Sliding-Window/01.Array-Sliding-Window.md
滑动窗口这里窗口的范围好像是左开右闭，这里写成[left，right)是不是好一些？

**Comment by itcharge** [comment]
> https://github.com/itcharge/LeetCode-Py/blob/b36df61e5824ca6248fb22acd26bc451ea965c9f/Contents/01.Array/05.Array-Sliding-Window/01.Array-Sliding-Window.md 滑动窗口这里窗口的范围好像是左开右闭，这里写成[left，right)是不是好一些？

这个看个人写法吧。两种其实都可以的，写习惯了都好。之前写的时候觉得携程左开右闭的话，需要考虑的情况可能会更加复杂。所以就用了左闭右闭区间。
