### ISSUE TITLE
建议增加前缀树相关知识

### ISSUE THREAD

**Issue by Whisht** [itcharge/LeetCode-Py#6]
建议在手册中增加前缀树相关的一些知识，这块内容在LeetCode也有不少题目可以用到的。

**Comment by itcharge** [comment]
> 建议在手册中增加前缀树相关的一些知识，这块内容在LeetCode也有不少题目可以用到的。

您好，目前手册中是有这部分内容的，链接为「[字典树知识](https://github.com/itcharge/LeetCode-Py/blob/main/Contents/06.String/03.String-Multi-Pattern-Matching/01.Trie.md)」，相关题目及题解链接为「[字典树题目](https://github.com/itcharge/LeetCode-Py/blob/main/Contents/06.String/03.String-Multi-Pattern-Matching/02.Trie-List.md)」。

**Comment by Whisht** [comment]
谢谢回复！
