### ISSUE TITLE
台灣無法開啟電子書網頁

### ISSUE THREAD

**Issue by catchfree1225** [itcharge/LeetCode-Py#99]
找不到 algo.itcharge.cn 
網頁找不到此網址的網頁：https://algo.itcharge.cn/
HTTP ERROR 404

目前只能用github md看解法，您的解析對我幫助很大
不過**網頁開不起來**
Chrome, Safari 都試過了，Mac電腦跟iOS手機也不行
不知道是什麼原因
謝謝作者

**Comment by itcharge** [comment]
已修复该问题
